### ISSUE TITLE
[Android] - Disconnecting from the conference without closing the session and then quick reconnect causes error

### ISSUE THREAD

**Issue by kszku-dolby** [DolbyIO/comms-sdk-flutter#226]
Environment:
SDK Version: 3.6.1 - https://github.com/DolbyIO/comms-sdk-flutter/releases/tag/3.6.1:
Client Platform: Flutter test app. 

Description/Steps-to-reproduce:
-Install the QA test app
-Connect to the conference Android device
-Disconnect from the conference WITHOUT closing the session
-Connect again to the same session 
-Do it multiple times cause it is not reproducible 100%
-You need at least 4 devices in the conference

Expected result:
The conference is reconnected properly

Actual result:
Connecting to the conference seems to fail after some time and "ERROR" appears. We can't go back to previous menu and we need to restart the app.  On iOS this issue seems to not exist. 

Devices:
DV-WRO-SAM96 Samsung Galaxy TAB S8 + Android 12
DV-WRO-SAM98 Samsung Galaxy Tab S8 Ultra + Android 12
DV-WRO-SAM90 Samsung S22 Plus + Android 12
Private Phone Poco X3 NFC + Android 12

**Comment by kbetl-dlb** [comment]
You mentions for devices in your test.Please let us know if this issue occurs on each of the devices or specific one ?

**Comment by kszku-dolby** [comment]
@kbetl-dlb each of the devices

**Comment by codlab** [comment]
this is currently an issue because the Android native SDK doesn't enforce an internal state when leaving and joining at the same time. A fix is pending for this.

A way to mitigate the issue would be to update the flutter sample app and make it call join only after the previous leave has been finished. I noticed that the current implementation make it so that the leave call is just thrown and never checked upon. Anyway a fix version should be either available as part as 3.7.4 (unlikely but depends on the timeframe) or 3.8

**Comment by codlab** [comment]
The Android SDK 3.7.3 should be fixing the issues regarding leave and join calls made in parallel by having the internal state managed transparently for developers, the flutter SDK will need to update the version used to ship this fix

**Comment by kbetl-dlb** [comment]
Cannot reproduce with android sdk 3.7.3
